// Writes the two loaders that carry the .wasm inline, as base64:
//
//   dist/concerto-engine.mjs  ESM (browsers, Node ESM): wasm-bindgen's `web`
//                             glue, instantiated with `initSync` at import.
//   dist/concerto-engine.cjs  CommonJS (Node 18 `require`): wasm-bindgen's
//                             `nodejs` glue with its readFileSync swapped for
//                             the inlined bytes.
//
// Either way the module is compiled and instantiated synchronously while the
// loader is evaluated, so `new Engine()` needs no `await`.
import { readFileSync, writeFileSync } from 'node:fs';

const NAME = 'concerto_wasm_spike';
const dist = new URL('../dist/', import.meta.url);
const wasm = readFileSync(new URL(`${NAME}_opt.wasm`, dist));
const b64 = wasm.toString('base64');

// Fastest decoder available: Uint8Array.fromBase64 (Node 24+, Chrome 140+),
// then Node's Buffer, then an atob loop (every browser; slow in old Node).
const decode = `
function decodeWasm(b64) {
  if (typeof Uint8Array.fromBase64 === 'function') return Uint8Array.fromBase64(b64);
  if (typeof Buffer === 'function') return Buffer.from(b64, 'base64');
  const s = atob(b64);
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}`;

// The web glue is ESM in a .js file.
writeFileSync(new URL('web/package.json', dist), '{ "type": "module" }\n');
writeFileSync(new URL('wasm-bytes.mjs', dist), `export default ${JSON.stringify(b64)};\n`);
writeFileSync(new URL('concerto-engine.mjs', dist), `// Generated by scripts/inline.mjs.
import { initSync } from './web/${NAME}.js';
import b64 from './wasm-bytes.mjs';
${decode}
const t0 = performance.now();
const bytes = decodeWasm(b64);
const t1 = performance.now();
const module = new WebAssembly.Module(bytes);
const t2 = performance.now();
initSync({ module });
const t3 = performance.now();
export const loadTimings = {
  decoder: typeof Uint8Array.fromBase64 === 'function' ? 'fromBase64' : typeof Buffer === 'function' ? 'Buffer' : 'atob',
  wasmBytes: bytes.length, decodeMs: t1 - t0, compileMs: t2 - t1, instantiateMs: t3 - t2 };
export * from './web/${NAME}.js';
`);

const glue = readFileSync(new URL(`node/${NAME}.js`, dist), 'utf8');
const needle = 'const wasmBytes = require(\'fs\').readFileSync(wasmPath);';
if (!glue.includes(needle)) throw new Error('nodejs glue changed shape: readFileSync line not found');
writeFileSync(new URL('concerto-engine.cjs', dist), glue
  .replace(`const wasmPath = \`\${__dirname}/${NAME}_bg.wasm\`;\n`, '')
  .replace(needle, `const wasmBytes = Buffer.from(${JSON.stringify(b64)}, 'base64');`));

console.log(`inlined ${wasm.length} bytes as ${b64.length} base64 chars`);
