// Writes the two loaders that carry the .wasm inline, as base64 (spike
// REPORT §1 and "Input to P4-01"), and the package.json that names them
// `@accordproject/concerto-engine`:
//
//   pkg/concerto-engine.mjs  wasm-bindgen's `web` glue, instantiated with
//                            `initSync` when the module is evaluated
//   pkg/concerto-engine.cjs  wasm-bindgen's `nodejs` glue, with its
//                            readFileSync swapped for the inlined bytes
//
// Both are ready as soon as they are loaded. Both also export an async
// `init()`: the browser fallback (spike REPORT §2) for a main thread that
// refuses a synchronous compile (Chromium's limit is 8 MiB); it compiles
// asynchronously, then instantiates with `initSync`. Once the module is
// instantiated, `init()` resolves at once.
import { readFileSync, writeFileSync, rmSync } from 'node:fs';

const NAME = 'concerto_wasm';
const pkg = new URL('../pkg/', import.meta.url);
const wasm = readFileSync(new URL(`${NAME}.wasm`, pkg));
const b64 = wasm.toString('base64');

// Decoder order: Uint8Array.fromBase64, then Buffer, then atob.
const decode = `
function decodeWasm(b64) {
  if (typeof Uint8Array.fromBase64 === 'function') return Uint8Array.fromBase64(b64);
  if (typeof Buffer === 'function') return Buffer.from(b64, 'base64');
  const s = atob(b64);
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}`;

writeFileSync(new URL('web/package.json', pkg), '{ "type": "module" }\n');
writeFileSync(new URL('concerto-engine.mjs', pkg), `// Generated by concerto-wasm/scripts/inline.mjs.
import { initSync } from './web/${NAME}.js';
${decode}
const bytes = decodeWasm(${JSON.stringify(b64)});
let ready = false;
try {
  initSync({ module: new WebAssembly.Module(bytes) });
  ready = true;
} catch (e) {
  // A main thread that refuses a synchronous compile of this size; call init().
  if (!(e instanceof RangeError)) throw e;
}
export async function init() {
  if (!ready) {
    initSync({ module: await WebAssembly.compile(bytes) });
    ready = true;
  }
}
export * from './web/${NAME}.js';
`);

const glue = readFileSync(new URL(`node/${NAME}.js`, pkg), 'utf8');
const needle = "const wasmBytes = require('fs').readFileSync(wasmPath);";
if (!glue.includes(needle)) {
  throw new Error('nodejs glue changed shape: readFileSync line not found');
}
writeFileSync(new URL('concerto-engine.cjs', pkg), `// Generated by concerto-wasm/scripts/inline.mjs.\n${glue
  .replace(`const wasmPath = \`\${__dirname}/${NAME}_bg.wasm\`;\n`, '')
  .replace(needle, `const wasmBytes = Buffer.from(${JSON.stringify(b64)}, 'base64');`)}
// Node compiles synchronously at any size: the module is ready once required.
module.exports.init = async function init() {};
`);
rmSync(new URL('node/', pkg), { recursive: true });

writeFileSync(new URL('package.json', pkg), `${JSON.stringify({
  name: '@accordproject/concerto-engine',
  private: true,
  version: '0.0.0',
  description: 'The concerto-core Rust engine as WASM (concerto-rust concerto-wasm); linked locally, not published',
  license: 'Apache-2.0',
  main: 'concerto-engine.cjs',
  module: 'concerto-engine.mjs',
  exports: { import: './concerto-engine.mjs', require: './concerto-engine.cjs' },
}, null, 2)}\n`);

console.log(`inline.mjs: ${wasm.length} bytes of wasm, ${b64.length} base64 characters`);
