// Writes the loaders of the optimised module, pkg/concerto_wasm.wasm, and
// the package.json that names them `@accordproject/concerto-engine`:
//
//   pkg/concerto-engine.cjs       Node `require`: wasm-bindgen's `nodejs`
//                                 glue, reading the raw .wasm next to it
//                                 with readFileSync
//   pkg/concerto-engine.node.mjs  Node `import`: the `web` glue,
//                                 instantiated with `initSync` from the raw
//                                 .wasm, read with readFileSync
//   pkg/concerto-engine.mjs       browsers: the `web` glue, instantiated
//                                 with `initSync` from the .wasm inlined as
//                                 base64 (spike REPORT §1)
//
// All three are ready as soon as they are loaded: Node reads and compiles
// the raw .wasm synchronously (P5-44, accordproject/concerto-rust#365). The
// browser loader keeps the inlined bytes until BC-32's explicit `await
// init()` (P5-45, #366) loads the raw .wasm there.
//
// All three also export an async `init()`. In the browser loader it is the
// fallback (spike REPORT §2) for a main thread that refuses a synchronous
// compile (Chromium's limit is 8 MiB): it compiles asynchronously, then
// instantiates with `initSync`. Once the module is instantiated, `init()`
// resolves at once.
import { readFileSync, writeFileSync, rmSync } from 'node:fs';

const NAME = 'concerto_wasm';
const pkg = new URL('../pkg/', import.meta.url);
const wasm = readFileSync(new URL(`${NAME}.wasm`, pkg));
const b64 = wasm.toString('base64');

// Decoder order: Uint8Array.fromBase64, then Buffer, then atob.
const decode = `
function decodeWasm(b64) {
  if (typeof Uint8Array.fromBase64 === 'function') return Uint8Array.fromBase64(b64);
  if (typeof Buffer === 'function') return Buffer.from(b64, 'base64');
  const s = atob(b64);
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}`;

writeFileSync(new URL('web/package.json', pkg), '{ "type": "module" }\n');
writeFileSync(new URL('concerto-engine.mjs', pkg), `// Generated by concerto-wasm/scripts/inline.mjs.
import { initSync } from './web/${NAME}.js';
${decode}
const bytes = decodeWasm(${JSON.stringify(b64)});
let ready = false;
try {
  initSync({ module: new WebAssembly.Module(bytes) });
  ready = true;
} catch (e) {
  // A main thread that refuses a synchronous compile of this size; call init().
  if (!(e instanceof RangeError)) throw e;
}
export async function init() {
  if (!ready) {
    initSync({ module: await WebAssembly.compile(bytes) });
    ready = true;
  }
}
export * from './web/${NAME}.js';
`);

// Node, both forms: the raw module read synchronously from pkg/, next to
// the loaders.
writeFileSync(new URL('concerto-engine.node.mjs', pkg), `// Generated by concerto-wasm/scripts/inline.mjs.
import { readFileSync } from 'node:fs';
import { initSync } from './web/${NAME}.js';
// Node compiles synchronously at any size: the module is ready once imported.
initSync({ module: readFileSync(new URL('./${NAME}.wasm', import.meta.url)) });
export async function init() {}
export * from './web/${NAME}.js';
`);

const glue = readFileSync(new URL(`node/${NAME}.js`, pkg), 'utf8');
const needle = `const wasmPath = \`\${__dirname}/${NAME}_bg.wasm\`;`;
if (!glue.includes(needle)) {
  throw new Error('nodejs glue changed shape: wasmPath line not found');
}
writeFileSync(new URL('concerto-engine.cjs', pkg), `// Generated by concerto-wasm/scripts/inline.mjs.\n${glue
  .replace(needle, `const wasmPath = \`\${__dirname}/${NAME}.wasm\`;`)}
// Node compiles synchronously at any size: the module is ready once required.
module.exports.init = async function init() {};
`);
rmSync(new URL('node/', pkg), { recursive: true });

writeFileSync(new URL('package.json', pkg), `${JSON.stringify({
  name: '@accordproject/concerto-engine',
  private: true,
  version: '0.0.0',
  description: 'The concerto-core Rust engine as WASM (concerto-rust concerto-wasm); linked locally, not published',
  license: 'Apache-2.0',
  main: 'concerto-engine.cjs',
  module: 'concerto-engine.mjs',
  exports: {
    browser: './concerto-engine.mjs',
    node: { import: './concerto-engine.node.mjs', require: './concerto-engine.cjs' },
    import: './concerto-engine.mjs',
    require: './concerto-engine.cjs',
  },
}, null, 2)}\n`);

console.log(`inline.mjs: ${wasm.length} bytes of wasm, ${b64.length} base64 characters in the browser loader`);
